//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int InvoiceId { get; set; }
        public string InvoiceMessage { get; set; }
        public string CustomerReferene { get; set; }
        public string UserDefinedField { get; set; }
    }
}
